config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :posts
  root 'posts#index' 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_attached_file :image, styles: { large: "600x600>",medium: "300x300>", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_locale
 
def set_locale
  I18n.locale = params[:locale] || I18n.default_locale
end
end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :kontrol]
  before_action :authenticate_user! ,only:[:new, :edit, :destroy]
  before_action :authenticate_user!
  before_action :kontrol,only:[:edit,:destroy]
    def kontrol
      unless @posts==current_user
      redirect_to posts_path, notice:"Yetki Problemi" unless current_user==@post.user
      end
    end
  
  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :msg, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Web</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body >

  <%= yield %>
</div>


<style>
.tt{
  cursor: pointer;
	color: white;
	display: block;
	padding: 10px;
	margin: 3px;
  
}

.geri{
  cursor: pointer;
	color: #555;
	display: block;
	padding: 10px;
	margin: 3px;
  
}

body{
  background-color:green;
  background-image:url(http://i.hizliresim.com/o9ZdLq.jpg);
 
}
.degisken{
  text-align:center;
  color:red;
}


.ss{
  background-color:white;
}


.bb{
  background-color:white;
  }
</style>


</body>
</html>


 

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :msg %><br>
    <%= f.text_area :msg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Yorum Düzenle</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container " >
  <div class="row " >
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a target="" href="http://www.galatasaray.org/anasayfa"><h1>GALATASARAY</h1></a>
          
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li class="btn btn-success navbar-btn btn-circle"><a href="#"><%=t ("ANASAYFA")%></a></li>
          <li><a href="#"><%=t ("FUTBOL")%></a></li>
          <li><a href="#"><%=t ("BASKETBOL")%></a></li>
          <li><a target="" href="http://www.gsstore.org/">GSTORE</a></li>
          <a href="?locale=tr">English</a>
          <a href="?locale=en">Turkish</a>
          <a href="?locale=fr">French</a>
          
          <li><%= link_to t('Cikis'), destroy_user_session_path, :method => :delete %></li>
        </ul>
      </div>
    </nav>
  </div>
 
 
 <div class="about" id="about">
    <div class="container">
    <div class="about-heading">
      <h2>Hakkında</h2>
  </div>
        
    <div class="row">
      <div class="col-md-6 about-left">
        <br><br>
        <img src="http://img-fanatik.mncdn.com/mnresize/980/565/images/16x9/2018/01/10/5248841.jpg" height="400px" width="560px"/>
    </div>
        <br><br><br>
    <div class="col-md-6 about-right ss">
      
        <h3>Galatasaray Odeabank, Oktay Mahmuti ile anlaştı</h3>
          <p>
              Erman Kunter ile yollarını ayıran Galatasaray Odeabank, Oktay Mahmuti ile anlaşmaya vardı.
              7DAYS EuroCup ve Tahincioğlu Basketbol Süper Ligi takımı Galatasaray Odeabank'ın yeni başantrenörü netlik kazandı.
              Beklentilerin çok uzağında bir sezon geçiren Sarı-Kırmızılı takım, Erman Kunter'den boşalan başantrenörlük koltuğunu Oktay Mahmuti'ye emanet etti.
              Avrupa'nın önemli basketbol muhabiri David Pick, Galatasaraylı yetkililerin, Oktay Mahmuti ile anlaştıklarını doğruladıklarını yazdı.
              Cim Bom'un, Mahmuti ile 1.5 yıllık anlaşmaya vardığı belirtildi
              
              Kariyerinde birçok takımda görev yapan 49 yaşındaki basketbol antrenörü, 2010-2012 yılları arasında da Galatasaray'da görev yapmışt
        </p>
    </div>
        
        
         <div class="clearfix"></div>
        </div>
  </div>
    </div>
 
 
  
  
  
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover bb">
       <br>
       <br>
       <br>
       <br>
       <br>
       <br>
        <thead>
          <tr>
            <th><%=t ("Title")%></th>
            <th><%=t ("Msg")%></th>
            <th colspan="4"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.title %></td>
              <td><%= post.msg %></td>
              <td><%= image_tag post.image.url(:thumb) %></td>
              <td><%= link_to t('Show'), post %></td>
              <td><%= link_to t('Edit'), edit_post_path(post) %></td>
              <td><%= link_to t('Destroy'), post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      
      <%= link_to t('Yeni yorum'), new_post_path, :action => "index",:class => "btn btn-inverse"%>
  
      
    </div>
    <div class="col-md-5">
      <br>
       <br>
       <br>
       <br>
       <br>
       <br>
       
    
      
  </div> </div>
  
  

<div class="degisken">
<% request.env.each do |key, value| %>
 <strong><%= key %></strong> => <%= value %><br/>
<% end %>
</div>

<div class="row">
 
    <footer class="container-fluid bg-4 text-center">
      <div class="well">
        <p>HAKAN KARAHALİL</p>
      </div>
    </footer>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<h1>YENİ YORUM</h1>

<%= render 'form' %>
<div class="geri">
<%= link_to 'GERİ', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @post.image.url(:medium) %>
<p>
  <div class="tt">
  <strong>BASLİK:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>MESAJ:</strong>
  <%= @post.msg %>
</p>


<%= link_to 'DÜZENLE', edit_post_path(@post) %> |
<%= link_to 'GERİ', posts_path %>
</div>